require(JGR)
require(rJava)
require(simdat.base)
setwd("~/Documents/RForge/simdat/pkg/simdat-gui/R")
source("allGenerics.R")
source("utils.R")
source("changeVariables.R")
source("changeModels.R")
#source("wizardDataModels.R")
source("wizardModels.R")
source("zzz.R")

#tmp <- ANOVA()

.jinit()
.jengine(TRUE)
.jaddClassPath("/home/maarten/Dropbox/simdat-gui/simdat/dist/simdat.jar")
#.jaddClassPath("/home/maarten/Dropbox/simdat-gui/simdat/dist/simdat.jar")
.jaddClassPath("/home/maarten/Dropbox/JavaGUI/deducer.jar")
#.jaddClassPath("/home/maarten/Dropbox/JavaGUI/quaqua.jar")
.simdat <- .jnew("simdat/SimDat",FALSE)
simdat.gui.env <- new.env()

.jcall(.simdat,,"startNoJGR")
assign("tmp",ANOVA(design=data.frame(A=factor(c(1,1,2,2),labels=c("A1","A2")),B=factor(c(1,2,1,2),labels=c("B1","B2"))),DV=list(name="Y",min=-Inf,max=Inf,digits=8),N=c(20,20,20,20),mu=c(10,20,20,30),sigma=c(5,5,5,5),family=NO()),simdat.gui.env)
assign("tmp2",GLM(factors=data.frame(A=factor(c(1,1,2,2),labels=c("A1","A2")),B=factor(c(1,2,1,3),labels=c("B1","B2","B3"))),covariates=VariableList(list(RandomIntervalVariable(numeric(60),digits=8,min=-Inf,max=Inf,name="X"))),covariateModels=ModelList(list(NormalModel(mean=0,sd=1))),N=c(15,15,15,15),mu=c(0,1,2,3),sigma=c(2,2,2,2),nu=NULL,tau=NULL,beta=c(1,1,1,1),DV=list(name="Y",min=-Inf,max=Inf,digits=8),family=NO()),simdat.gui.env)
#.jcall(.simdat,,"eval","tmp <- ANOVA()")
.jcall(.simdat,,"refreshModels")
.jcall(.simdat,,"startViewerAndWait")

