require(JGR)
require(simdat.base)
setwd("~/Documents/RForge/simdat/pkg/simdat-gui/R")
source("allGenerics.R")
source("utils.R")
source("changeVariables.R")
source("changeModels.R")
source("wizardDataModels.R")
source("zzz.R")

tmp <- ANOVA()

.jinit()
.jengine(TRUE)
.jaddClassPath("/home/maarten/Dropbox/simdat-gui/simdat/dist/simdat.jar")
.jaddClassPath("/home/maarten/Documents/deducer.jar")
.simdat <- .jnew("simdat/SimDat",FALSE)
simdat.gui.env <- new.env()

.jcall(.simdat,,"startNoJGR")
assign("tmp",ANOVA(),simdat.gui.env)
#.jcall(.simdat,,"eval","tmp <- ANOVA()")
.jcall(.simdat,,"refreshModels")
.jcall(.simdat,,"startViewerAndWait")
