setGeneric("isMetric",function(object,...) standardGeneric("isMetric"))
setGeneric("isRandom",function(object,...) standardGeneric("isRandom"))
setGeneric("simulateFromModel",function(object,model,nsim=1,seed,...) standardGeneric("simulateFromModel"))
#setGeneric("simulate",function(object,nsim=1,seed,...) standardGeneric("simulate"))
#setGeneric("N",function(object,...) standardGeneric("N"))
#setGeneric("N<-",function(object,value,...) standardGeneric("N<-"))
#setGeneric("mean",function(object,...) standardGeneric("mean"))
#setGeneric("mean<-",function(x,value,...) standardGeneric("mean<-"))
#setGeneric("sigma",function(object,...) standardGeneric("sigma"))
#setGeneric("sd<-",function(x,value,...) standardGeneric("sd<-"))
#setGeneric("var<-",function(x,value,...) standardGeneric("var<-"))
#setGeneric("design",function(object,...) standardGeneric("design"))
#setGeneric("design<-",function(object,value,...) standardGeneric("design<-"))
#setGeneric("designData",function(object,...) standardGeneric("designData"))
setGeneric("digits",function(object,...) standardGeneric("digits"))
#setGeneric("scale",function(object,...) standardGeneric("scale"))
setGeneric("getData",function(object,...) standardGeneric("getData"))
setGeneric("variableNames",function(object,...) standardGeneric("variableNames"))
setGeneric("variableNames<-",function(object,value,...) standardGeneric("variableNames<-"))

setGeneric("asRandom",function(object,...) standardGeneric("asRandom"))
setGeneric("asFixed",function(object,...) standardGeneric("asFixed"))

setGeneric("min<-",function(object,value,...) standardGeneric("min<-"))
setGeneric("max<-",function(object,value,...) standardGeneric("max<-"))
setGeneric("digits<-",function(object,value,...) standardGeneric("digits<-"))

setGeneric("models",function(object,...) standardGeneric("models",...))
setGeneric("models<-",function(object,value,...) standardGeneric("models<-",...))

setGeneric("variables",function(object,...) standardGeneric("variables",...))
setGeneric("variables<-",function(object,value,...) standardGeneric("variables<-",...))

#setGeneric("asNominal",function(object,...) standardGeneric("as.Nominal"))
#setGeneric("as.Ordinal",function(object,...) standardGeneric("as.Ordinal"))
#setGeneric("as.Interval",function(object,...) standardGeneric("as.Interval"))
#setGeneric("as.Ratio",function(object,...) standardGeneric("as.Ratio"))
